version: 2
jobs:
    build-client:
        docker:
            - image: circleci/node:12

        working_directory: ~/PlanarAlly/client

        steps:
            - checkout:
                  path: ~/PlanarAlly

            - restore_cache:
                  key: npm-{{ checksum "package-lock.json" }}
                  name: Restoring npm cache

            - run:
                  name: npm install
                  command: npm i

            - save_cache:
                  key: npm-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node-modules

            - run:
                  name: Build artifacts
                  command: npm run build

            - persist_to_workspace:
                  root: ../
                  paths:
                      - server

    release-server:
        docker:
            - image: cibuilds/github:0.13.0

        working_directory: ~/PlanarAlly

        steps:
            - attach_workspace:
                  at: ./

            - run:
                  name: Create tmp folder
                  command: mkdir /tmp/archives

            - run:
                  name: Zip artifacts
                  command: |
                      VERSION=$(cat server/VERSION)
                      zip -r /tmp/archives/planarally-bin-${VERSION}.zip server/*

            - run:
                  name: Gunzip artifacts
                  command: |
                      VERSION=$(cat server/VERSION)
                      tar -czf /tmp/archives/planarally-bin-${VERSION}.tar.gz server/*

            - run:
                  name: "Publish release on github"
                  command: |
                      VERSION=$(cat server/VERSION)
                      ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -replace ${VERSION} /tmp/archives

workflows:
    version: 2
    build:
        jobs:
            - build-client:
                  filters:
                      branches:
                          ignore: /.*/
                      tags:
                          only: /^\d+\.\d+\.\d+[-a-zA-Z0-9]*$/
            - release-server:
                  requires:
                      - build-client
                  filters:
                      branches:
                          ignore: /.*/
                      tags:
                          only: /^\d+\.\d+\.\d+[-a-zA-Z0-9]*$/
